### PR TITLE
Use alpine:latest to keep up with clang releases

### PR DESCRIPTION
**Pull request by Jakuje**

### CODE REVIEW

**Comment by yshui** [comment]
i think it's better to have a pinned version rather than latest. to avoid unexpected breakages.

**Comment by Jakuje** [comment]
> i think it's better to have a pinned version rather than latest. to avoid unexpected breakages.

I think this is fair point. There are changes between clang versions.

Would it make sense then to pin to alpine 3.16 or 3.17 before the 3.14 will go EOL on 2023-05-01?

**Comment by Jakuje** [comment]
Or create a separate "old" branch or tag to keep stable clang version and in master follow the `alpine:latest`?

**Comment by yshui** [comment]
It's now pinned to 3.17.

Thank you for bringing this to my attention!

**Pull request closed without merging**
